board/urls.py


from django.contrib import admin
from django.urls import path, include

from . import views

#'board' is not a registered namespace
app_name='board' #이렇게 써줘야 없어진다  

urlpatterns = [
    path('', views.index),
     
    # myhome/urls.py - path('board/', include('board.urls')),
    # 내가 받은 url중에 /board ~~~ 시작하는 url이 있으면 이거는 
    # board 폴더아래에 있는 urls.py  가 처리하라 
    
    path('list', views.list, name="list"),#http://127.0.0.1/board/list 
    path('write', views.write, name="write"), #http://127.0.0.1/board/write 
    path('save', views.save, name="save"), #http://127.0.0.1/board/save 
    
    path('view/<int:id>', views.view, name="view"), #http://127.0.0.1/board/view/1 
    
    path('modify/<int:id>', views.modify, name="modify"), 
    #get방식으로 보내면 board_write.html에 디비 불러온거 그냥 뿌리고 
    #post방식으로 보내면 update를 실행한다 

    path('delete/<int:id>', views.delete, name="delete"),
    path('ChkDeleteAll', views.ChkDeleteAll, name="ChkDeleteAll") 
    
]

common/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name='common' 

urlpatterns = [
    path('', views.base),
    path('index', views.index, name='common_index'), 
    path('list', views.list, name="common_list"),    
    path('save', views.save, name="common_save"),     
    path('view/<int:id>', views.view, name="common_view"), 
    path('delete/<int:id>', views.delete, name="common_delete"),
    
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'), 

    
    # path('ChkDeleteAll', views.ChkDeleteAll, name="ChkDeleteAll"), #개발중

]

myhome/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


from board import views

urlpatterns = [
    
    path('', include('common.urls')),
    path('common/', include('common.urls')),
] 
urlpatterns += static (settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) 
print(urlpatterns)

common/models.py
from django.db import models

# Create your models here.
class CoMmon(models.Model):
  id = models.AutoField(primary_key=True)
  img_name = models.CharField(max_length=200)
  date = models.CharField(max_length=20)
  time = models.DateTimeField()
  dron_id = models.CharField(max_length=20)
  address = models.CharField(max_length=200)
  x = models.CharField(max_length=50)
  y = models.CharField(max_length=50)
  ip_address = models.CharField(max_length=50)
  wdate = models.DateTimeField()

common/forms.py
#/project/myhome/board/forms.py

#html문서로부터 form 태그의 값들을 읽어서 python 객체로 전환시켜서 
#views.py파일에서 사용이 가능 
#html페이지의 form 태그와 models의   field를 서로 연결시켜준다. 
from django import forms 
from common.models import CoMmon
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class BoardForm(forms.ModelForm):
     class Meta:
        #중요요소 
        model = CoMmon #모델을 전달해줘야 서로 연결이 된다. 
        #모델과 폼을 연결시킬 필드들을 지정한다 - db에 있는 필드랑 똑같이 
        #board_write.html의 form태그안에 있는 태그들에 이 이름이 있어야 한다 
        fields = ['img_name', 'dron_id', 'time']
        labels = {'img_name':'제목', 'dron_id':'드론', 'time':'시간'}

class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "email")        

      

common/views.py
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
import base64
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from .forms import UserForm
import os
import time
import json
from common.CommonPage import dictfetchall, CommonPage
from django.db import connection
from .models import CoMmon 
from django.contrib.auth.decorators import login_required

def signup(request):
    """
    계정생성
    """
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('common:login')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})


def base(request):
    return render(request, "index.html")

@login_required(login_url='common:login')
def index(request):
    return render(request, "./common/index.html")


def get_today():
    now = time.localtime()
    s = "%04d%02d%02d" % (now.tm_year, now.tm_mon, now.tm_mday)
    s2 = "%04d%02d%02d_%02d%02d%02d" % (now.tm_year, now.tm_mon, now.tm_mday, now.tm_hour, now.tm_min, now.tm_sec)
    return s, s2+".png"
    
def make_folder(folder_name):
    if not os.path.isdir(folder_name):
        os.mkdir(folder_name)



from django.db import connection
@csrf_exempt   #csrf 토큰 에러 제거
def save(request):
    if (request.method == 'POST'):
        dron_id = request.POST.get('dron_id')   #드론넘버
        x = request.POST.get('x')               #X좌표
        y = request.POST.get('y')               #Y좌표
        address = request.POST.get('address_name')  #주소
        img_name = request.POST.get('img_name')      #이미지 받아오기
        ip_address = request.META.get('REMOTE_ADDR') #IP주소

        print(img_name)
        #폴더 만들고, /upload/2020/09/14/20200914_1234.png
        root_dir = "./upload"
        path, filename = get_today()
        work_dir = root_dir + "/" + path
        print(work_dir)
        
        make_folder(work_dir)

        #이미지저장 20200914_1234.png
        img_name = img_name.replace('data:image/png;base64,', '') #이미지이름  
        img_name = img_name.replace(' ', '+')                                
        d = base64.b64decode(img_name)   #base64방식으로 디코딩 작업
        file = open(work_dir+"/"+ filename, mode="wb")   #wb (b가 바이너리이기 때문에 꼭 써야 저장됨)
        file.write(d)
        file.close()
       

        #DB - 일련번호, 드론식별값, 이미지 path, 이미지명, 저장된 날짜시간분초, 상대방 IP
        cursor = connection.cursor()
        sql = f"""
        insert into common_common (date, time, dron_id, x, y, address, 
        img_name, ip_address, wdate) values ('{path}', now(), '{dron_id}', '{x}', '{y}', '{address}',
         '{filename}', '{request.META['REMOTE_ADDR']}', now())
        """      
        print(sql)
        cursor.execute(sql)
        
    return HttpResponse("saved")


@login_required(login_url='common:login')
def list(request):
    #int(request.GET.get('page', '1'))
    sel = request.GET.get('sel')
    key = request.GET.get('key')

    if sel == None : sel="1"
    if key == None : key=""
    
    if sel =="1":
        cond = f" where date like '%{key}%'  or dron_id = '%{key}%' "
    elif sel=="2":
        cond = f" where date like '%{key}%' " 
    elif sel=="3":
        cond = f" where dron_id like '%{key}%' " 
    else: 
        cond = " "

    cursor = connection.cursor()
    sql ="select count(*) from common_common " + cond
    cursor.execute(sql)
    totalCount = int(cursor.fetchone()[0]) #첫번째값 가져오기
    #http://127.0.0.1:8000/board/list?page=1
    curPage = int(request.GET.get('page','1'))
    #앞에 파리미터 (page)가 값이 지정되지 않으면 기본값을 줄 수 있다.
    #curPage = request.GET['page']

    commonPage = CommonPage(totalCount, curPage, 10)
    #데이터 가져올 위치값
    start = (curPage-1)*10 #페이지가 0부터 시작하므로 0~9->실제페이지:(1-10), 10~19(11-20)
    
    sql =f'''
    select id, img_name, dron_id, date, time, ip_address, date_format(wdate, '%Y-%m-%d %T') wdate
    from common_common {cond}
    order by id desc limit {start}, 10
    '''
    #limit 시작위치, 개수
    cursor = connection.cursor()
    cursor.execute(sql)       
    common_list = dictfetchall(cursor)
    #print(common_list)
     
    context = {'common_list':common_list, 'commonPage':commonPage, 'sel':sel, 'key':key,'page':curPage}
    return render(request, 'common/common_list.html', context)


@login_required(login_url='common:login') 
def view(request, id): # 게시판 항목을 누 르면 개별 항목에 대한 것을 볼 수 있게 하기
    #id2 = request.GET['id']
    #최신 : <a href="/board/view/1">제목1</a>
    
    page= int(request.GET.get('page', '1'))
    sel = request.GET.get('sel')
    key = request.GET.get('key')

    if sel == None : sel="1"
    if key == None : key=""


    
    
    cursor = connection.cursor()
              
    sql = f"""
    select id, img_name, dron_id, date, time, wdate, x, y, address, ip_address
    from common_common
    where id={id}
    """
    cursor.execute(sql)       
    common_item = dictfetchall(cursor)    
    context = {'id':id, 'common_item':common_item[0], 'sel':sel, 'key':key, 'page':page}
    return render(request, 'common/common_view.html', context)

from django.shortcuts import get_object_or_404

def delete(request, id):
    board_obj = get_object_or_404(CoMmon, pk=id) ####### 
    board_obj.delete()
    return redirect('common:common_list')    


@csrf_exempt
def deleteall(request):
    if (request.method == 'POST'):
        cursor = connection.cursor()

        data = request.POST.get('myJSON')
        ids = json.loads(data)
        print(ids)
        q = ', '.join(ids)
        print(q)
        sql = '''
                DELETE FROM common_common WHERE id IN ({})
            '''.format(q)

        print(sql)

        cursor.execute(sql)

    return redirect('common:common_list')
   

templates/common/common_list.html

<!-- ---------------------------------------- [edit] ---------------------------------------- -->
{% extends 'base.html' %}
{% block content %}
<!-- ---------------------------------------------------------------------------------------- -->

<form name="form" method="">
  <input type="hidden" name="sel" id="sel" value="{{sel}}">

<div class="container" style="margin-top:40px">
  <h3 >촬영 이미지 저장소</h3>
  <div style="height:30px"></div>
  
  <form name="form">

  <div class="input-group mt-3 mb-3">
  <div class="input-group-prepend">
    <button type="button" class="btn btn-outline-secondary dropdown-toggle" data-toggle="dropdown"  id="searchItem">
     	  전체
    </button>
    <div class="dropdown-menu">
      <a class="dropdown-item" href="#" onclick="changeSearch('1')">전체</a>
      <a class="dropdown-item" href="#" onclick="changeSearch('2')">date</a>
      <a class="dropdown-item" href="#" onclick="changeSearch('3')">dron_id</a>
    </div>
  </div>
  <input type="text" class="form-control" name="key" id="key" value="{{key}}" placeholder="검색어를 입력하세요">
  <div class="input-group-append">
    <button class="btn btn-success" type="button" onclick="goSearch()">Go</button>
  </div>
</div>


  <table class="table">
  	<colgroup>
  		<col width="4%"/>
  		<col width="6%">
  		<col width="*%"/>
  		<col width="8%"/>
      <col width="12%"/>
  		<col width="20%"/>
      <col width="12%"/>
  	</colgroup>
    <thead class="table-primary">
      <tr>
          
        <th><input type='checkbox' onchange='checkAll(this)'></th>    
        <th style="text-align:center">번호</th>
        
        <th style="text-align:center">실제이미지</th>
        <th style="text-align:center">img_name</th>
        <th style="text-align:center">dron_id</th>
        <th style="text-align:center">date</th>
        
        <th>ipaddress</th>
      </tr>
    </thead>
    <tbody>

		{%for common_item in common_list%}

        <tr>
       
            <td style="text-align:center; vertical-align: middle"><input type='checkbox' name='del' class='del' value='{{board.id}}'></td>
                        
            <td style="text-align:center; vertical-align: middle">{{common_item.id}}</td>
            <td><a href="/view/{{common_item.id}}?key={{key}}&sel={{sel}}&page={{page}}"><img class="img-thumbnail" style="width:200px; height:80px" src="\upload\{{common_item.date}}\{{common_item.img_name}}" ></a></td>
            <td style="text-align:center; vertical-align: middle"><a href="/view/{{common_item.id}}?key={{key}}&sel={{sel}}&page={{page}}">{{common_item.img_name}}</a></td> 
            <!-- common에 urls 내용에서 common_view를 지정해야 한다.-->
            
  			    <td style="text-align:center; vertical-align: middle">{{common_item.dron_id}}</td>
            
            <td style="text-align:center; vertical-align: middle">{{common_item.wdate}}</td>    
            <td style="text-align:center; vertical-align: middle">{{common_item.ip_address}}</td>    
            


        </tr>
		{%endfor%}  
    </tbody>
  </table>
{%include "paging.html" %}



	<div class="container" style="text-align:right">
	  <div class="btn-group">
	    <button type="button" class="btn btn-primary" onclick="goDeleteAll()" >삭제</button>
	  </div>
	</div>

  	
</form>
</div>
</body>
</html>

<script>
window.onload=goInit();

function goInit()
{
	
	//console.log({{sel}});
	changeSearch({{sel}});
	document.getElementById("key").value = '{{key}}';
	
}

function goPage(pg)
{
	frm = document.form;
	frm.pg.value=pg;
	frm.action="/list";
	frm.submit();
}


function goSearch()
{
  frm = document.form;
	frm.action="/list";
	frm.submit();
}

function changeSearch(sel)
{
	document.getElementById("sel").value = sel;
	
	if(sel=="1")
		sel="전체";
	else if(sel=="2")
		sel ="date";
	else if(sel=="3")
		sel ="dron_id";
		
	document.getElementById("searchItem").innerHTML = sel;
}

/*
function goDelete()
{
  if( confirm("삭제?") ){
    ChkDelete();
    frm = document.form;
    frm.method="post";
    frm.action="/common/ChkDelete";
    frm.submit();
  }
}
*/

function checkAll(e) {
    var checkboxes = document.getElementsByName('del');

    if (e.checked) {
      for (var i = 0; i < checkboxes.length; i++) {
        checkboxes[i].checked = true;
      }
    } else {
      for (var i = 0; i < checkboxes.length; i++) {
        checkboxes[i].checked = false;
      }
    }
  }

function goDeleteAll()
{
  var c = $('.del:checked');
  if (c.length > 0) {
    var arr = new Array();
    if (confirm("정말 삭제하시겠습니까?")) {
      for (var i=0; i < c.length; i++) {
        arr.push(c[i].value)
      }
      console.log(arr);
    }
    var myJSON = JSON.stringify(arr);

    $.ajax({
      url:'{% url 'common:common_list'%}',
      type:'POST',
      data: {'myJSON':myJSON}
    }).done(function(){})
  }
}











</script>

{% endblock %}

templates/common/common_view.html
{% extends 'base.html' %}
{% block content %}

<div class="container" style="margin-top:20px">
  <h2>촬영 이미지 상세보기</h2>
  <p></p>
  <form name="form">   
    <input type="hidden" name="sel" id="sel" value="{{sel}}">
    <input type="hidden" name="key" id="key" value="{{key}}">
    <input type="hidden" name="page" id="page" value="{{page}}">

  <table class="table">
  	<colgroup>
  		<col width="25%"/>
  		<col width="*"/>
  	</colgroup>
    
    <tbody>
            
     <tr>
      	<td>촬영일,시간 </td>
        <td>{{common_item.wdate}}
  		</td>
     </tr>
     <tr>
      	<td>드론 ID</td>
        <td>{{common_item.dron_id}}
  		</td>
     </tr>        
      <tr >
        <td>GPS(위도/경도)</td>
        <td>위도 :&nbsp;{{common_item.x}}&nbsp;&nbsp; 경도 :&nbsp;{{common_item.y}}</td>
     
      </tr>
      <tr >
        <td>주소</td>
        <td>{{common_item.address}}</td>
     
      </tr>
      <tr >
        <td>IP주소</td>
        <td>{{common_item.ip_address}}</td>
      </tr>
      <tr >
        <td>이미지명 </td>
        <td>{{common_item.img_name}}</td>
      
      </tr>
      <tr ><!-- <img src="\upload\2020\09\15\1\ -->
        <td>이미지 상세보기</td>
        <td><img src="\upload\{{common_item.date}}\{{common_item.img_name}}">
        </td>
      
      </tr>
     
       
       <tr >
        <td></td>
        <td></td>
      </tr>
      
    </tbody>
  </table>
  
  	<div class="container" style="text-align:right">
	  <div class="btn-group">
	    
	    
	    <button type="button" class="btn btn-danger"  onclick="goDelete()">삭제</button>&nbsp;&nbsp;
		  <button type="button" class="btn btn-primary" onclick="goList()">목록</button>
	  </div>
	</div>
</form>	
</div>

<script>

function goList(){
  frm = document.form; 
  frm.action="/common/list";
  frm.method="get";
  frm.submit();
}

function goDelete()
{
  frm = document.form; 
  frm.action="/common/delete/{{common_item.id}}";
  frm.method="get";
  frm.submit();
}

</script>

{% endblock %}

templates/common/index.html
<!-- ---------------------------------------- [edit] ---------------------------------------- -->
{% extends 'base.html' %}
{% block content %}
<!-- ---------------------------------------------------------------------------------------- -->
{% load static %}
<style>
body {
  font-family: sans-serif;
}

canvas {
  margin-left: 40px;
  max-width: 100%;
  width: 480px;
}

video {
  max-width: 100%;
  width: 480px;
}
</style>

<div class="container" style="margin-top:20px">
  <h1></h1>
  <p></p>
  
  {%csrf_token%}
  <h1>Realtime communication with WebRTC</h1>
  <p>
    <span id="Longitude"></span>
    <span id="Latitude"></span>
    <span id="addr_name"></span>
  </p>  

  <div id="videoCanvas" >
    <video id="camera" autoplay playsinline></video>
    <canvas id="photo"></canvas>
  </div>

  <div id="buttons" style="width:400px; margin-top:10px">
    <button  class="btn btn-primary" id="snapAndSend">Start</button> 
    &nbsp;&nbsp;&nbsp;&nbsp;
    <button  class="btn btn-primary" id="stop">stop</button>
    &nbsp;&nbsp;&nbsp;&nbsp;
    <span>interval</span>
    <select name="interval" id="interval" onchange="snapPhoto()">
      <option value="1000">선택</option>
      <option value="3000">3초</option>
      <option value="5000">5초</option>
    </select>

  </div>

  <p id="longitude">
  </p>
  
  <script src="https://webrtc.github.io/adapter/adapter-latest.js"></script>
  <script src="{% static '/js/main.js' %}"></script> <!--경로 static/js/main.js-->

</body>

</html>
<script>
  $(document).ready(function(){
    console.log("ddd")
    grabWebCamVideo();
  });
  </script>

  {% endblock %}

templates/common/login.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <div class="row">
        <div class="col-4">
            <h4>로그인</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'common:signup' %}">계정을 만드세요.</a></span>
        </div>
    </div>
    <form method="post" class="post-form" action="{% url 'common:login' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock %}

templates/common/signup.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <div class="row my-3">
        <div class="col-4"><h4>계정생성</h4></div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'common:login' %}">로그인 하세요.</a></span>
        </div>
    </div>
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자 이름</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>
{% endblock %}