board/urls.py


from django.contrib import admin
from django.urls import path, include

from . import views

#'board' is not a registered namespace
app_name='board' #이렇게 써줘야 없어진다  

urlpatterns = [
    path('', views.index),
     
    # myhome/urls.py - path('board/', include('board.urls')),
    # 내가 받은 url중에 /board ~~~ 시작하는 url이 있으면 이거는 
    # board 폴더아래에 있는 urls.py  가 처리하라 
    
    path('list', views.list, name="list"),#http://127.0.0.1/board/list 
    path('write', views.write, name="write"), #http://127.0.0.1/board/write 
    path('save', views.save, name="save"), #http://127.0.0.1/board/save 
    
    path('view/<int:id>', views.view, name="view"), #http://127.0.0.1/board/view/1 
    
    path('modify/<int:id>', views.modify, name="modify"), 
    #get방식으로 보내면 board_write.html에 디비 불러온거 그냥 뿌리고 
    #post방식으로 보내면 update를 실행한다 

    path('delete/<int:id>', views.delete, name="delete"),
    path('ChkDeleteAll', views.ChkDeleteAll, name="ChkDeleteAll") 
    
]

common/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name='common' 

urlpatterns = [
    path('', views.base),
    path('index', views.index, name='common_index'), 
    path('list', views.list, name="common_list"),    
    path('save', views.save, name="common_save"),     
    path('view/<int:id>', views.view, name="common_view"), 
    path('delete/<int:id>', views.delete, name="common_delete"),
    
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'), 

    
    # path('ChkDeleteAll', views.ChkDeleteAll, name="ChkDeleteAll"), #개발중

]

myhome/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


from board import views

urlpatterns = [
    
    path('', include('common.urls')),
    path('common/', include('common.urls')),
] 
urlpatterns += static (settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) 
print(urlpatterns)

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    
    <title>1조 프로젝트</title>
</head>
<body>
{%include "navibar.html"%}

<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
</body>
<script>
function goLogin()
{
  
  location.href="/login";
  
}
</script>

</html>

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/index.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <title>1조 프로젝트</title>
</head>
<body>
  <!--메뉴바가 navibar.html에 있는데 이걸 포함시켜라 -->
<div class="container" style="margin-top:20px">
  <h1>(1조) 자율비행 드론 관제소 : 자동 촬영 DB 웹 서버 구현</h1>

    </li>

<div class="container" style="text-align:right">
	  <div class="btn-group">
	    <button type="button" class="btn btn-primary" onclick="goLogin()" >시작</button>
	  </div>
	</div>

</body>
</html>
<script>
function goLogin()
{
  
  location.href="/login";
  
}
</script>

templates/navibar.html
<!-- navigation bar 추가 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="#">1조 자율비행드론</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item"><a  class="nav-link" href="{%url 'common:common_list' %}">목록</a></li>
            <li class="nav-item"><a  class="nav-link" href="{%url 'common:common_index' %}">촬영</a></li>
            <li class="nav-item"><a  class="nav-link" href="{%url 'common:logout' %}">로그아웃</a></li>
        </ul>
    </div>
</nav>

templates/navibar_old.html
<!-- navigation bar 추가 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'blog:list' %}">Blog</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
        
            <li class="nav-item ">
               {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                {% else %}
                <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>

templates/paging.html
<ul class="pagination justify-content-center">

  {% if commonPage.isPrev %}
  <li class="page-item">
  <a class="page-link" href="?page={{commonPage.previous_page_number}}">
  이전</a>
  </li>
  {%else%}
    <li class="page-item">
    <a class="page-link" href="#" aria-disabled="ture">
    이전</a>
  </li>
  {%endif%}

  
  {%for page_num in commonPage.page_range%}
    {%if page_num == commonPage.curPage%}
      <li class="page-item active">
        <a class="page-link" aria-current ="page"
            href="?page={{page_num}}">{{page_num}}</a>
            </li>
    {%else%}            
      <li class="page-item">
          <a class="page-link" 
              href="?page={{page_num}}">{{page_num}}</a>
              </li>
    {%endif%}
  {%endfor%}              
  

  {% if commonPage.isNext %}
  <li class="page-item">
  <a class="page-link" href="?page={{commonPage.next_page_number}}">
  다음</a>
  </li>
  {%else%}
    <li class="page-item">
    <a class="page-link" href="#" aria-disabled="ture">
    다음</a>
  </li>
  {%endif%}


</ul>